// <auto-generated />
using BiografiaAspNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BiografiaAspNet.Migrations
{
    [DbContext(typeof(BiografiaAspNetDbContext))]
    partial class BiografiaAspNetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BiografiaAspNet.Models.DadosPessoais", b =>
                {
                    b.Property<int>("DadosPessoaisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataNascimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DadosPessoaisID");

                    b.ToTable("DadosPessoais");
                });

            modelBuilder.Entity("BiografiaAspNet.Models.ExpProfissional", b =>
                {
                    b.Property<int>("ExpProfissionalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DadosPessoaisID")
                        .HasColumnType("int");

                    b.Property<string>("Entidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funcoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpProfissionalID");

                    b.HasIndex("DadosPessoaisID");

                    b.ToTable("ExperienciaProfissional");
                });

            modelBuilder.Entity("BiografiaAspNet.Models.ExpProfissional", b =>
                {
                    b.HasOne("BiografiaAspNet.Models.DadosPessoais", "Nome")
                        .WithMany()
                        .HasForeignKey("DadosPessoaisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
